### ISSUE TITLE
Missing check for player only commands.

### ISSUE THREAD

**Issue by Feryc-Projects** [MagmaGuy/FreeMinecraftModels#3]
CommandHandler.java is missing a check to see if the executor is actually a player resulting in

fmm spawn static <id>
[12:36:03 WARN]: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @5ce65a89)
[12:36:03 WARN]:        at FreeMinecraftModels.jar//com.magmaguy.freeminecraftmodels.commands.CommandHandler.lambda$constructCommands$5(CommandHandler.java:85)
[12:36:03 WARN]:        at FreeMinecraftModels.jar//cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[12:36:03 WARN]:        at FreeMinecraftModels.jar//cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[12:36:03 WARN]:        at FreeMinecraftModels.jar//cloud.commandframework.CommandManager.executeCommand(CommandManager.java:188)
[12:36:03 WARN]:        at FreeMinecraftModels.jar//cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
[12:36:03 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[12:36:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
[12:36:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:972)
[12:36:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:500)
[12:36:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[12:36:03 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[12:36:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[12:36:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:36:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[12:36:03 INFO]: [Example] An internal error occurred while attempting to perform this command.

**Comment by MagmaGuy** [comment]
Pretty sure I have fixed this since.
